name: vcard
description: A dart port of vCard JS by Eric J Nesser. Create vCards to import contacts into Outlook, iOS, Mac OS, and Android devices from your website or mobile application.
version: 0.1.0
author: Valery Colong<valery.colong@activspaces.com>
homepage: https://github.com/valerycolong/vcard

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0
  path_provider: ^2.0.15
  path: ^1.8.3
  intl: 0.18.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
